version: "3"


services:
  server:
    name: serv
    build: server/.
    command: python3 ./server.py
#    ports:
#      - 127.0.0.1:2000:2000
      #- 2000:2000
    network_mode: host

  client:
    build: client/
    command: python3 ./client.py http://localhost:2000
    #command: python3 ./client.py http://server:2000
    network_mode: host
    depends_on:
      - server


networks:
  default:
    external: false
    name: sona_default     
